graph_generator:
  map_yaml: "maps/track.yaml"
  output_dir: "data"
  graph_name: "track_graph.npz"

  xy_resolution: 0.10
  theta_resolution: 0.2617993878  # 15 degrees
  vehicle_length: 0.50
  vehicle_width: 0.25
  safety_margin: 0.1
