controller:
  ros__parameters:
    waypoint_file: "/home/vaithak/Downloads/UPenn/F1Tenth/sim_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    # waypoint_file: "/home/nvidia/f1tenth_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    is_sim: True
    # is_sim: False
    plot_debug: True

opponent_detection:
  ros__parameters:
    waypoint_file: "/home/vaithak/Downloads/UPenn/F1Tenth/sim_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    # waypoint_file: "/home/nvidia/f1tenth_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    is_sim: True
    # is_sim: False
    plot_debug: True

opponent_tracking:
  ros__parameters:
    waypoint_file: "/home/vaithak/Downloads/UPenn/F1Tenth/sim_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    # waypoint_file: "/home/nvidia/f1tenth_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    is_sim: True
    # is_sim: False
    plot_debug: True

spline_node:
  ros__parameters:
    waypoint_file: "/home/vaithak/Downloads/UPenn/F1Tenth/sim_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    # waypoint_file: "/home/nvidia/f1tenth_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    is_sim: True
    # is_sim: False
    plot_debug: True

state_machine:
  ros__parameters:
    waypoint_file: "/home/vaithak/Downloads/UPenn/F1Tenth/sim_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    # waypoint_file: "/home/nvidia/f1tenth_ws/src/f1tenth_icra_race/waypoints/race3-manual-fitted.csv"
    is_sim: True
    # is_sim: False
    plot_debug: True

# ros2 run f1tenth_icra_race controller.py --ros-args -p is_sim:=True -p waypoint_file:=/home/navjot/Desktop/work/sim_ws/src/r3/f1tenth-icra-race/waypoints/race3-manual-fitted.csv
# ros2 run f1tenth_icra_race opponent_detection_node_cpp --ros-args -p is_sim:=True -p waypoint_file:=/home/navjot/Desktop/work/sim_ws/src/r3/f1tenth-icra-race/waypoints/race3-manual-fitted.csv
# ros2 run f1tenth_icra_race opponent_tracking.py --ros-args -p is_sim:=True -p waypoint_file:=/home/navjot/Desktop/work/sim_ws/src/r3/f1tenth-icra-race/waypoints/race3-manual-fitted.csv
# ros2 run f1tenth_icra_race spliner.py --ros-args -p is_sim:=True -p waypoint_file:=/home/navjot/Desktop/work/sim_ws/src/r3/f1tenth-icra-race/waypoints/race3-manual-fitted.csv
# ros2 run f1tenth_icra_race state_machine.py --ros-args -p is_sim:=True -p waypoint_file:=/home/navjot/Desktop/work/sim_ws/src/r3/f1tenth-icra-race/waypoints/race3-manual-fitted.csv
    
